apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sockshop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emreeaarslan/sock-shop-gitops.git
    targetRevision: main
    path: apps/sockshop
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
