apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sockshop
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop

  sources:
    - repoURL: https://github.com/emreeaarslan/microservices-demo.git
      targetRevision: main
      path: helm-chart
      helm:
        releaseName: sockshop
        valueFiles:
          - $values/apps/sockshop/values.yaml

    - repoURL: https://github.com/emreeaarslan/sock-shop-gitops.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true